# Generated by Django 5.0.4 on 2024-05-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RMPathKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RMPathContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl1papp.rmpathkey')),
            ],
        ),
    ]
